### ISSUE TITLE
Cannot start GUI if the service is started

### ISSUE THREAD

**Issue by girion01** [ChangemakerStudios/Papercut#125]
When running Papercut as a service on win 2012 R2 it is not possible to start the user interface. It seems like the user interface tries to start a server on port 25 regardless if it is taken or not. The workaround is to stop the service in the services panel before starting the user interface. This becomes an issue especially on a shared test environment.

**Comment by bplumlee-sh** [comment]
We're experiencing the same issue. Getting FileLoadException from the client when attempting to load the plugin DLLs while the service is running. The client runs file if we stop the service.
[PapercutCoreFailure-20180830.json.txt](https://github.com/ChangemakerStudios/Papercut/files/2337162/PapercutCoreFailure-20180830.json.txt)

**Comment by redfellow** [comment]
Also the service seems to take a good while to load. Had to go make a cuppa after updating the app to get the service back running again.

**Comment by cyphix333** [comment]
Just experienced this too, no errors, program just wouldn't open.

**Comment by cyphix333** [comment]
Yeah, I couldn't even get it working tbh... don't know if I was doing anything wrong, but wasn't getting any mail.

**Comment by redfellow** [comment]
That's the service being in `stopped` state. You can check by hitting `WIN+R` and typing `services.msc`. From there, locate PaperCut SMTP Service and notice that it's not running.

**Comment by marietteknap** [comment]
I set the Papercut Service to Delayed Start and that fixed it for me.

**Comment by jennings** [comment]
I think this may have been caused by commit 920463d8. This set the default JsonSerializerSettings.Formatting to Indented. This means [Papercut.exe is now sending formatted JSON to Papercut.Service.exe](https://github.com/ChangemakerStudios/Papercut/blob/b24c12d0eb3715174b1eba6329fbf1b42af252f7/src/Papercut.Network/PapercutClient.cs#L164-L170). But since the service [processes incoming data one line at a time](https://github.com/ChangemakerStudios/Papercut/blob/b24c12d0eb3715174b1eba6329fbf1b42af252f7/src/Papercut.Network/Protocols/StringCommandProtocol.cs#L58-L62)

So the sequence of events seems to be:

1. Papercut.exe connects to Papercut.Service.exe and sends a JSON-formatted PapercutProtocolRequest.
2. Papercut.Service.exe decodes this data as UTF-8 and reads the first line, which is just "{".
3. [Papercut.Service.exe throws a JsonSerializationException here](https://github.com/ChangemakerStudios/Papercut/blob/b24c12d0eb3715174b1eba6329fbf1b42af252f7/src/Papercut.Network/Protocols/PapercutProtocol.cs#L73). Since the catch handler is only catching IOException, the socket is not closed and no reply is sent.
4. Meanwhile, [Papercut.exe blocks waiting for a response on the socket](https://github.com/ChangemakerStudios/Papercut/blob/b24c12d0eb3715174b1eba6329fbf1b42af252f7/src/Papercut.Network/PapercutClient.cs#L172), which never comes.

I think passing a `JsonSerializerSettings` to the `ToJson` method would be the most straightforward way to fix this.

---

Below is the exception I'm getting in Papercut.Service's log file. It shows that we're trying to deserialize the incomplete string "{".

```
2018-11-29 11:59:05.982 -08:00 [Debug] New Connection 2 from "127.0.0.1:60824"
2018-11-29 11:59:06.232 -08:00 [Debug] Received Line "{"
2018-11-29 11:59:06.232 -08:00 [Warning] Failed to End Receive on Async Socket
Newtonsoft.Json.JsonSerializationException: Unexpected end when reading JSON. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Papercut.Network.Protocols.PapercutProtocol.ProcessRequest(String incomingRequest) in C:\projects\papercut\src\Papercut.Network\Protocols\PapercutProtocol.cs:line 73
   at Papercut.Network.Protocols.StringCommandProtocol.ProcessIncomingBuffer(Byte[] bufferedData, Encoding encoding) in C:\projects\papercut\src\Papercut.Network\Protocols\StringCommandProtocol.cs:line 64
   at Papercut.Network.Connection.ContinueProcessReceive(IAsyncResult result) in C:\projects\papercut\src\Papercut.Network\Connection.cs:line 138
```

**Comment by kallebornemark** [comment]
@Jaben Was this issue closed because it was resolved?
