### ISSUE TITLE
Fails to load Manifest from CodePlex

### ISSUE THREAD

**Issue by RickStrahl** [ChangemakerStudios/Papercut#94]
Starting PaperCut after a long time of not running it and get this error:

	* Activation of C:\Users\rstrahl\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Papercut\Papercut.appref-ms| resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from https://archive.codeplex.com/?p=papercut: the manifest may not be valid or the file could not be opened.
		+ DTD is prohibited in this XML document.

I suspect this is due to CodePlex shutting down.

IAC the app no longer starts I just get the **Cannot Start Application** dialog.

Uninstalled and reinstalled latest release from here with the same result.

Here's the full error trace
```
PLATFORM VERSION INFO
	Windows 			: 10.0.16299.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2556.0 built by: NET471REL1
	clr.dll 			: 4.7.2600.0 built by: NET471REL1LAST
	dfdll.dll 			: 4.7.2556.0 built by: NET471REL1
	dfshim.dll 			: 10.0.16299.15 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/XXXXX/AppData/Roaming/Microsoft/Windows/Start%20Menu/Programs/Papercut/Papercut.appref-ms%7C

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\xxxx\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Papercut\Papercut.appref-ms| resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from https://archive.codeplex.com/?p=papercut: the manifest may not be valid or the file could not be opened.
		+ DTD is prohibited in this XML document.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [2/11/2018 4:50:11 PM] : Activation of C:\Users\XXXX\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Papercut\Papercut.appref-ms| has started.
	* [2/11/2018 4:50:11 PM] : Performing necessary update check as specified by the deployment.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2/11/2018 4:50:12 PM] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from https://archive.codeplex.com/?p=papercut: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifest(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentUpdate(SubscriptionState& subState, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Xml.XmlException
		- DTD is prohibited in this XML document.
		- Source: System.Xml
		- Stack trace:
			at System.Xml.XmlTextReaderImpl.Throw(Exception e)
			at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
			at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
			at System.Deployment.Application.ManifestValidatingReader.XmlFilteredReader.Read()
			at System.Xml.XsdValidatingReader.Read()
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
```

**Comment by RickStrahl** [comment]
Just noticed that the zip install appears to be a full standalone install and that works. Thanks :-)

Still probably need to address the issue of the EXE installer not working out of box.
